apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-defj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-defj
    app.kubernetes.io/part-of: test-app-fxcg
  name: test-component-defj
  namespace: build-e2e-hacbs-xclg
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-defj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-defj
    spec:
      containers:
      - image: quay.io/mkovarik/test-images:9aa7886dc7a64e978ced8146707d631b
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
